### ISSUE TITLE
Style all admonitions

### ISSUE THREAD

**Issue by irskep** [irskep/sphinx-better-theme#24]

**Comment by tomghyselinck** [comment]
Hi,

We also found some missing styling of for example *todo* admonitions.

I tried this in my `better.css` (which looks quite good in style with the better theme):

```css
.admonition-todo {
    background-color: #ffe4c4;
    border: 1px solid #f66;
}

.admonition-todo tt {
    background: #efb4b4;
}
```

- Is there anyone interested in working on this?
- Is there a list of admonitions which needs to be updated/improved?
- Is there any other related issue I should be aware of?

Thanks!
